// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PersonalisationEngine.Api.Data;

#nullable disable

namespace PersonalisationEngine.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260601095323_SeedPlayers")]
    partial class SeedPlayers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PersonalisationEngine.Api.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageStake")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DaysSinceJoined")
                        .HasColumnType("integer");

                    b.Property<string>("FavouriteTeam")
                        .HasColumnType("text");

                    b.Property<bool>("IsInCoolingOff")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSelfExcluded")
                        .HasColumnType("boolean");

                    b.Property<int>("LastLoginDaysAgo")
                        .HasColumnType("integer");

                    b.Property<string>("MostBetSport")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MostBetType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
